version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "AD"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql